### ISSUE TITLE
Fix Tkinter version App

### ISSUE THREAD

**Issue by openedhardware** [joshuad31/TandaPay-Simulation#4]
We need a test that has the minimum number of random or chance events.

The inputs are here - https://docs.google.com/spreadsheets/d/1h1Q_MOxYqpC2BPCEUXdaXMp8qcrZZlpZKBFbL0A57fo/edit#gid=1617600984

Need to update the tkinter app to get the same result with main.py

**Comment by joshuad31** [comment]
@openedhardware It works!  Thank you
